name: Run unit tests
on: [pull_request, workflow_dispatch]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Svelte Kit Sync
        run: npx svelte-kit sync

      - name: Run tests
        run: npm run test:unit
